name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Build
        env:
          NEXT_PUBLIC_SITE_URL: https://world-time-app-omega.vercel.app
        run: npm run build
      - name: Unit tests (Jest)
        run: npm test -- --ci --reporters=default --reporters=jest-junit
      - name: Upload Jest Report
        uses: actions/upload-artifact@v4
        with:
          name: jest-report
          path: junit.xml
          if-no-files-found: ignore
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: E2E (Playwright)
        run: npm run test:e2e || npx playwright test --reporter=junit
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

